import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// 2024년 기출 스타일 문제 (year:2024, round:1~3)
// 응용 문제 (year:2024, round:99, isGenerated:true)
const questions2024 = [
  // ===== 소프트웨어 설계 2024년 1회 =====
  { year:2024, round:1, subject:'소프트웨어 설계', questionNo:1,
    content:'UML 다이어그램 중 시스템과 외부 액터 간 상호작용을 나타내는 다이어그램은?',
    optionA:'클래스 다이어그램', optionB:'유스케이스 다이어그램', optionC:'시퀀스 다이어그램', optionD:'상태 다이어그램',
    answer:2, difficulty:'EASY', topic:'UML 다이어그램',
    explanation:'유스케이스 다이어그램은 시스템과 외부 액터(사용자, 외부 시스템) 간의 기능적 상호작용을 표현합니다. 클래스 다이어그램은 구조, 시퀀스 다이어그램은 객체 간 메시지 흐름을 나타냅니다.',
    tags:JSON.stringify(['UML', '유스케이스']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 설계', questionNo:2,
    content:'소프트웨어 설계의 원칙 중 하나인 추상화(Abstraction)에 대한 설명으로 옳은 것은?',
    optionA:'모듈 간의 의존성을 최소화하는 원칙', optionB:'불필요한 세부사항을 숨기고 핵심 개념만 표현하는 것',
    optionC:'하나의 모듈이 하나의 기능만 수행하는 원칙', optionD:'클래스를 상속받아 재사용하는 것',
    answer:2, difficulty:'EASY', topic:'소프트웨어 설계 원칙',
    explanation:'추상화는 복잡한 내부 구현을 숨기고 핵심 개념과 인터페이스만 노출하는 설계 원칙입니다. 정보 은닉(Information Hiding)과 함께 모듈화 설계의 핵심입니다.',
    tags:JSON.stringify(['추상화', '설계원칙']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 설계', questionNo:3,
    content:'GoF 디자인 패턴 중 행위(Behavioral) 패턴에 해당하지 않는 것은?',
    optionA:'옵서버(Observer)', optionB:'전략(Strategy)', optionC:'프록시(Proxy)', optionD:'커맨드(Command)',
    answer:3, difficulty:'MEDIUM', topic:'디자인 패턴',
    explanation:'프록시(Proxy)는 구조(Structural) 패턴입니다. 행위 패턴에는 옵서버, 전략, 커맨드, 반복자, 템플릿 메서드, 책임 연쇄, 상태, 방문자, 중재자, 메멘토, 인터프리터가 있습니다.',
    tags:JSON.stringify(['디자인패턴', 'GoF', '행위패턴']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 설계', questionNo:4,
    content:'SOLID 원칙 중 "소프트웨어 엔티티는 확장에는 열려 있고 수정에는 닫혀 있어야 한다"는 원칙은?',
    optionA:'단일 책임 원칙(SRP)', optionB:'개방-폐쇄 원칙(OCP)', optionC:'리스코프 치환 원칙(LSP)', optionD:'인터페이스 분리 원칙(ISP)',
    answer:2, difficulty:'EASY', topic:'SOLID 원칙',
    explanation:'OCP(Open-Closed Principle)는 기존 코드를 수정하지 않고 기능을 확장할 수 있도록 설계해야 한다는 원칙입니다. 추상화와 다형성을 활용합니다.',
    tags:JSON.stringify(['SOLID', 'OCP']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 설계', questionNo:5,
    content:'애자일 개발 방법론 중 2주~4주 단위의 반복 개발 사이클을 스프린트(Sprint)라고 부르는 것은?',
    optionA:'XP(익스트림 프로그래밍)', optionB:'칸반(Kanban)', optionC:'스크럼(Scrum)', optionD:'린(Lean)',
    answer:3, difficulty:'EASY', topic:'애자일 방법론',
    explanation:'스크럼(Scrum)은 스프린트라는 반복 주기(1~4주)로 개발하는 애자일 프레임워크입니다. 스프린트 계획, 데일리 스크럼, 스프린트 리뷰, 레트로스펙티브가 핵심 이벤트입니다.',
    tags:JSON.stringify(['애자일', '스크럼']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 설계', questionNo:6,
    content:'소프트웨어 아키텍처 패턴 중 사용자 인터페이스, 비즈니스 로직, 데이터를 분리하여 각 레이어가 독립적으로 역할을 담당하는 패턴은?',
    optionA:'이벤트 기반(Event-Driven)', optionB:'마이크로서비스(Microservices)', optionC:'계층형(Layered)', optionD:'파이프-필터(Pipe-Filter)',
    answer:3, difficulty:'EASY', topic:'아키텍처 패턴',
    explanation:'계층형(Layered) 아키텍처는 프레젠테이션, 비즈니스, 데이터 접근 계층으로 나누는 패턴입니다. MVC 패턴도 이 범주에 속하며 가장 널리 사용되는 아키텍처입니다.',
    tags:JSON.stringify(['아키텍처', '계층형']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 설계', questionNo:7,
    content:'소프트웨어 결합도(Coupling) 중 가장 낮은 결합도(좋은 설계)는?',
    optionA:'내용 결합도(Content Coupling)', optionB:'공통 결합도(Common Coupling)', optionC:'스탬프 결합도(Stamp Coupling)', optionD:'메시지 결합도(Message Coupling)',
    answer:4, difficulty:'MEDIUM', topic:'결합도와 응집도',
    explanation:'결합도 낮은 순서: 메시지 < 자료 < 스탬프 < 제어 < 외부 < 공통 < 내용. 메시지 결합도(Message Coupling)는 파라미터를 통한 데이터만 전달하여 가장 느슨하게 연결됩니다.',
    tags:JSON.stringify(['결합도', '모듈설계']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 설계', questionNo:8,
    content:'요구사항 분석 기법 중 현재 시스템의 문제점을 분석하고 새로운 시스템의 개선 방향을 도출하기 위해 사용하는 기법은?',
    optionA:'프로토타이핑(Prototyping)', optionB:'인터뷰(Interview)', optionC:'JAD(Joint Application Design)', optionD:'유스케이스 분석',
    answer:1, difficulty:'MEDIUM', topic:'요구사항 분석',
    explanation:'프로토타이핑은 요구사항이 불분명할 때 초기 모델을 빠르게 만들어 사용자 피드백을 받으며 요구사항을 명확히 하는 기법입니다. 반복적 개발로 요구사항 변경에 유연합니다.',
    tags:JSON.stringify(['요구사항', '프로토타이핑']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 설계', questionNo:9,
    content:'UML 관계 중 클래스 A가 클래스 B를 포함하며, B가 A 없이는 존재할 수 없는 강한 포함 관계는?',
    optionA:'연관(Association)', optionB:'집합(Aggregation)', optionC:'합성(Composition)', optionD:'의존(Dependency)',
    answer:3, difficulty:'MEDIUM', topic:'UML 관계',
    explanation:'합성(Composition)은 강한 포함 관계로, 부분(B)이 전체(A)에 종속됩니다. A가 삭제되면 B도 함께 삭제됩니다. 집합(Aggregation)은 약한 포함 관계로 B가 독립적으로 존재 가능합니다.',
    tags:JSON.stringify(['UML', '합성', '집합']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 설계', questionNo:10,
    content:'마이크로서비스 아키텍처(MSA)의 특징으로 옳지 않은 것은?',
    optionA:'서비스별 독립적 배포 가능', optionB:'서비스 간 API로 통신', optionC:'단일 데이터베이스 공유', optionD:'서비스별 독립적 확장 가능',
    answer:3, difficulty:'MEDIUM', topic:'마이크로서비스',
    explanation:'MSA는 각 서비스가 자체 데이터베이스를 보유합니다(Database per Service 패턴). 단일 DB 공유는 모놀리식 아키텍처의 특징입니다.',
    tags:JSON.stringify(['MSA', '마이크로서비스']), sourceNote:'2024년 1회 스타일' },

  // ===== 소프트웨어 개발 2024년 1회 =====
  { year:2024, round:1, subject:'소프트웨어 개발', questionNo:1,
    content:'이진 탐색(Binary Search)을 수행하기 위한 전제 조건은?',
    optionA:'데이터가 연결 리스트로 저장되어 있어야 한다', optionB:'데이터가 정렬되어 있어야 한다',
    optionC:'데이터의 개수가 짝수여야 한다', optionD:'데이터가 해시 테이블에 저장되어 있어야 한다',
    answer:2, difficulty:'EASY', topic:'탐색 알고리즘',
    explanation:'이진 탐색은 정렬된 배열에서 중간값과 비교하여 탐색 범위를 절반씩 줄여나가는 알고리즘입니다. 시간복잡도는 O(log n)이며, 정렬이 선행되어야 합니다.',
    tags:JSON.stringify(['이진탐색', '알고리즘']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 개발', questionNo:2,
    content:'소프트웨어 테스트 중 명세 기반 기법(블랙박스 테스트)에 해당하는 것은?',
    optionA:'구문 커버리지(Statement Coverage)', optionB:'분기 커버리지(Branch Coverage)',
    optionC:'동등 분할(Equivalence Partitioning)', optionD:'경로 커버리지(Path Coverage)',
    answer:3, difficulty:'EASY', topic:'소프트웨어 테스트',
    explanation:'동등 분할은 입력 데이터를 동등한 클래스로 나누어 테스트하는 블랙박스(명세 기반) 기법입니다. 구문/분기/경로 커버리지는 코드 내부 구조를 기반으로 하는 화이트박스 기법입니다.',
    tags:JSON.stringify(['테스트', '블랙박스', '동등분할']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 개발', questionNo:3,
    content:'시간 복잡도가 O(n log n)인 정렬 알고리즘을 모두 고른 것은?',
    optionA:'버블 정렬, 삽입 정렬', optionB:'퀵 정렬, 병합 정렬, 힙 정렬',
    optionC:'선택 정렬, 버블 정렬', optionD:'기수 정렬, 계수 정렬',
    answer:2, difficulty:'MEDIUM', topic:'정렬 알고리즘',
    explanation:'퀵 정렬(평균 O(n log n)), 병합 정렬(O(n log n)), 힙 정렬(O(n log n))이 O(n log n) 복잡도를 가집니다. 버블/삽입/선택 정렬은 O(n²), 기수/계수 정렬은 O(nk)입니다.',
    tags:JSON.stringify(['정렬', '시간복잡도']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 개발', questionNo:4,
    content:'스택(Stack) 자료구조의 특성을 올바르게 설명한 것은?',
    optionA:'FIFO(First In First Out) 구조', optionB:'LIFO(Last In First Out) 구조',
    optionC:'우선순위에 따라 데이터 추출', optionD:'양쪽 끝에서 삽입/삭제 가능',
    answer:2, difficulty:'EASY', topic:'자료구조',
    explanation:'스택은 LIFO(Last In First Out) 구조로, 마지막에 삽입된 데이터가 먼저 삭제됩니다. 함수 호출, 괄호 검사, 깊이우선탐색(DFS)에 활용됩니다. FIFO는 큐(Queue)의 특성입니다.',
    tags:JSON.stringify(['스택', 'LIFO', '자료구조']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 개발', questionNo:5,
    content:'Git 명령어 중 원격 저장소의 변경사항을 로컬로 가져와 자동으로 병합하는 명령어는?',
    optionA:'git fetch', optionB:'git clone', optionC:'git pull', optionD:'git merge',
    answer:3, difficulty:'EASY', topic:'버전 관리',
    explanation:'git pull은 git fetch + git merge를 합친 명령어로, 원격 저장소의 변경사항을 가져와 현재 브랜치에 자동 병합합니다. git fetch는 변경사항만 가져오고 병합은 하지 않습니다.',
    tags:JSON.stringify(['Git', '버전관리']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 개발', questionNo:6,
    content:'트리(Tree)에서 특정 노드의 왼쪽과 오른쪽 서브트리를 모두 갖출 수 있는 이진 트리 순회 방법 중 루트를 가장 먼저 방문하는 것은?',
    optionA:'중위 순회(Inorder)', optionB:'후위 순회(Postorder)', optionC:'전위 순회(Preorder)', optionD:'레벨 순회(Level-order)',
    answer:3, difficulty:'MEDIUM', topic:'트리 자료구조',
    explanation:'전위 순회(Preorder)는 루트→왼쪽→오른쪽 순으로 방문합니다. 중위 순회(Inorder)는 왼쪽→루트→오른쪽, 후위 순회(Postorder)는 왼쪽→오른쪽→루트 순입니다.',
    tags:JSON.stringify(['트리', '순회', '자료구조']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 개발', questionNo:7,
    content:'소프트웨어 품질 측정 지표 중 코드 복잡도를 측정하는 맥케이브(McCabe) 복잡도의 계산 방법은?',
    optionA:'코드 라인 수 / 모듈 수', optionB:'간선 수 - 노드 수 + 2',
    optionC:'결함 수 / 코드 라인 수 × 1000', optionD:'테스트 케이스 수 / 요구사항 수',
    answer:2, difficulty:'HARD', topic:'소프트웨어 품질',
    explanation:'맥케이브 순환 복잡도 = E - N + 2 (E: 간선 수, N: 노드 수). 또는 V(G) = 판단 노드 수 + 1로 계산합니다. 복잡도가 낮을수록(10 이하 권장) 유지보수가 쉽습니다.',
    tags:JSON.stringify(['맥케이브', '복잡도', '품질']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 개발', questionNo:8,
    content:'테스트 주도 개발(TDD)의 올바른 개발 사이클은?',
    optionA:'설계 → 구현 → 테스트', optionB:'테스트 작성 → 구현 → 리팩토링',
    optionC:'구현 → 테스트 → 배포', optionD:'분석 → 설계 → 구현 → 테스트',
    answer:2, difficulty:'EASY', topic:'개발 방법론',
    explanation:'TDD(Test-Driven Development)는 Red(실패하는 테스트 작성) → Green(테스트를 통과하는 최소 코드 구현) → Refactor(리팩토링) 사이클로 개발합니다.',
    tags:JSON.stringify(['TDD', '테스트주도개발']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 개발', questionNo:9,
    content:'해시(Hash) 충돌 해결 방법 중 충돌 발생 시 다음 빈 슬롯을 순차적으로 찾는 방법은?',
    optionA:'체이닝(Chaining)', optionB:'선형 탐사(Linear Probing)', optionC:'이중 해싱(Double Hashing)', optionD:'버킷(Bucket) 해싱',
    answer:2, difficulty:'MEDIUM', topic:'해시 자료구조',
    explanation:'선형 탐사(Linear Probing)는 충돌 시 다음 인접 슬롯을 순서대로 탐색합니다. 체이닝은 연결 리스트를 사용하고, 이중 해싱은 두 번째 해시 함수로 이동 거리를 결정합니다.',
    tags:JSON.stringify(['해시', '충돌해결']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'소프트웨어 개발', questionNo:10,
    content:'소프트웨어 형상 관리(SCM)의 주요 기능이 아닌 것은?',
    optionA:'버전 관리(Version Control)', optionB:'변경 제어(Change Control)',
    optionC:'빌드 자동화(Build Automation)', optionD:'형상 감사(Configuration Audit)',
    answer:3, difficulty:'MEDIUM', topic:'형상 관리',
    explanation:'형상 관리(SCM)의 4가지 기능: 형상 식별, 변경 제어, 형상 감사, 형상 상태 보고. 빌드 자동화는 CI/CD 영역으로 형상 관리의 직접적인 기능은 아닙니다.',
    tags:JSON.stringify(['형상관리', 'SCM']), sourceNote:'2024년 1회 스타일' },

  // ===== 데이터베이스 구축 2024년 1회 =====
  { year:2024, round:1, subject:'데이터베이스 구축', questionNo:1,
    content:'데이터베이스 정규화 과정에서 부분 함수 종속을 제거하는 정규형은?',
    optionA:'제1정규형(1NF)', optionB:'제2정규형(2NF)', optionC:'제3정규형(3NF)', optionD:'보이스-코드 정규형(BCNF)',
    answer:2, difficulty:'MEDIUM', topic:'정규화',
    explanation:'제2정규형(2NF)은 1NF를 만족하면서 모든 비키 속성이 기본키 전체에 완전 함수 종속되어야 합니다. 복합 기본키의 일부에만 종속되는 부분 함수 종속을 제거합니다.',
    tags:JSON.stringify(['정규화', '2NF']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'데이터베이스 구축', questionNo:2,
    content:'SQL에서 집계 함수와 함께 사용하여 그룹에 조건을 적용하는 절은?',
    optionA:'WHERE', optionB:'ORDER BY', optionC:'HAVING', optionD:'GROUP BY',
    answer:3, difficulty:'EASY', topic:'SQL',
    explanation:'HAVING 절은 GROUP BY로 그룹화된 결과에 조건을 적용합니다. WHERE는 그룹화 전 행에 조건을 적용합니다. 실행 순서: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY',
    tags:JSON.stringify(['SQL', 'HAVING', 'GROUP BY']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'데이터베이스 구축', questionNo:3,
    content:'관계형 데이터베이스에서 외래키(Foreign Key)에 대한 설명으로 옳지 않은 것은?',
    optionA:'참조 무결성을 유지하는 데 사용된다', optionB:'다른 테이블의 기본키를 참조한다',
    optionC:'반드시 NOT NULL이어야 한다', optionD:'CASCADE 옵션으로 연쇄 삭제가 가능하다',
    answer:3, difficulty:'MEDIUM', topic:'관계형 DB',
    explanation:'외래키는 NULL 값을 허용할 수 있습니다(선택적 관계). 예를 들어 직원 테이블의 부서 외래키는 부서가 미정인 경우 NULL일 수 있습니다.',
    tags:JSON.stringify(['외래키', '참조무결성']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'데이터베이스 구축', questionNo:4,
    content:'트랜잭션의 격리성(Isolation)이 완전히 보장되지 않을 때 발생할 수 있는 문제로 옳지 않은 것은?',
    optionA:'더티 리드(Dirty Read)', optionB:'반복 불가능한 읽기(Non-Repeatable Read)',
    optionC:'팬텀 리드(Phantom Read)', optionD:'데드락(Deadlock)',
    answer:4, difficulty:'HARD', topic:'트랜잭션',
    explanation:'격리성 부재로 발생하는 문제: 더티 리드, 반복 불가능한 읽기, 팬텀 리드. 데드락은 격리성과 무관하게 두 트랜잭션이 서로의 자원을 기다리는 교착 상태입니다.',
    tags:JSON.stringify(['트랜잭션', '격리성', '이상현상']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'데이터베이스 구축', questionNo:5,
    content:'SQL의 DDL(Data Definition Language) 명령어가 아닌 것은?',
    optionA:'CREATE', optionB:'ALTER', optionC:'DROP', optionD:'UPDATE',
    answer:4, difficulty:'EASY', topic:'SQL DDL',
    explanation:'UPDATE는 DML(Data Manipulation Language) 명령어입니다. DDL에는 CREATE(생성), ALTER(수정), DROP(삭제), TRUNCATE(전체 삭제), RENAME이 있습니다.',
    tags:JSON.stringify(['SQL', 'DDL', 'DML']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'데이터베이스 구축', questionNo:6,
    content:'데이터베이스 인덱스(Index)에 대한 설명으로 옳지 않은 것은?',
    optionA:'검색 속도를 향상시킨다', optionB:'INSERT/UPDATE/DELETE 성능을 저하시킬 수 있다',
    optionC:'추가적인 저장 공간이 필요하다', optionD:'모든 컬럼에 인덱스를 생성하면 성능이 최적화된다',
    answer:4, difficulty:'MEDIUM', topic:'인덱스',
    explanation:'인덱스를 과도하게 생성하면 데이터 변경 시 인덱스 업데이트 오버헤드가 증가하고 저장 공간이 낭비됩니다. 선택적으로 WHERE, JOIN 조건에 자주 사용되는 컬럼에만 생성해야 합니다.',
    tags:JSON.stringify(['인덱스', 'DB최적화']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'데이터베이스 구축', questionNo:7,
    content:'NoSQL 데이터베이스의 특징으로 옳지 않은 것은?',
    optionA:'수평적 확장(Scale-Out)이 용이하다', optionB:'스키마리스(Schemaless) 구조를 지원한다',
    optionC:'반드시 ACID를 완전히 보장한다', optionD:'대용량 분산 데이터 처리에 적합하다',
    answer:3, difficulty:'MEDIUM', topic:'NoSQL',
    explanation:'NoSQL은 일반적으로 ACID보다 완화된 BASE(Basically Available, Soft state, Eventually consistent) 모델을 사용합니다. 가용성과 확장성을 ACID 일관성보다 우선시합니다.',
    tags:JSON.stringify(['NoSQL', 'BASE', 'ACID']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'데이터베이스 구축', questionNo:8,
    content:'다음 SQL의 실행 결과로 올바른 것은?\nSELECT COUNT(DISTINCT dept) FROM employee WHERE salary > 3000;',
    optionA:'급여가 3000 초과인 행의 총 개수', optionB:'급여가 3000 초과인 직원의 부서 수(중복 제거)',
    optionC:'모든 직원의 부서 수', optionD:'급여가 3000 초과인 부서별 평균 급여',
    answer:2, difficulty:'MEDIUM', topic:'SQL 집계함수',
    explanation:'DISTINCT는 중복을 제거하고, COUNT는 NULL이 아닌 행의 수를 셉니다. 이 쿼리는 급여가 3000 초과인 직원들이 속한 부서의 종류 수(중복 제거)를 반환합니다.',
    tags:JSON.stringify(['SQL', 'COUNT', 'DISTINCT']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'데이터베이스 구축', questionNo:9,
    content:'데이터베이스 뷰(View)의 특징으로 옳지 않은 것은?',
    optionA:'논리적 데이터 독립성을 제공한다', optionB:'실제 데이터를 저장한다',
    optionC:'보안 목적으로 사용할 수 있다', optionD:'복잡한 쿼리를 단순화할 수 있다',
    answer:2, difficulty:'EASY', topic:'뷰(View)',
    explanation:'뷰(View)는 실제 데이터를 저장하지 않는 가상 테이블입니다. 기본 테이블의 데이터를 SELECT 쿼리 결과로 보여주며, 데이터는 기본 테이블에만 저장됩니다. 단, 인덱스된 뷰(물리적 뷰)는 예외입니다.',
    tags:JSON.stringify(['뷰', 'View']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'데이터베이스 구축', questionNo:10,
    content:'ER 다이어그램에서 다대다(M:N) 관계를 관계형 데이터베이스로 변환할 때 필요한 것은?',
    optionA:'두 엔터티 중 하나에 외래키 추가', optionB:'새로운 중간 테이블(교차 엔터티) 생성',
    optionC:'두 엔터티를 하나의 테이블로 통합', optionD:'기본키를 복합키로 변경',
    answer:2, difficulty:'MEDIUM', topic:'ER 다이어그램',
    explanation:'M:N 관계는 직접 표현 불가하여 두 엔터티의 기본키를 외래키로 가지는 중간 교차 테이블을 생성합니다. 예: 학생-수강-과목 관계에서 수강 테이블이 교차 테이블입니다.',
    tags:JSON.stringify(['ER다이어그램', 'M:N관계']), sourceNote:'2024년 1회 스타일' },

  // ===== 프로그래밍 언어 활용 2024년 1회 =====
  { year:2024, round:1, subject:'프로그래밍 언어 활용', questionNo:1,
    content:'다음 C언어 코드의 출력 결과는?\n#include <stdio.h>\nint main() {\n  int a = 10, b = 3;\n  printf("%d %d", a/b, a%b);\n}',
    optionA:'3 1', optionB:'3.3 1', optionC:'3 0', optionD:'4 1',
    answer:1, difficulty:'EASY', topic:'C언어',
    explanation:'정수형 나눗셈: 10/3 = 3(몫), 10%3 = 1(나머지). C언어에서 정수형 변수끼리의 나눗셈은 소수점을 버리고 정수 몫만 반환합니다.',
    tags:JSON.stringify(['C언어', '연산자']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'프로그래밍 언어 활용', questionNo:2,
    content:'OSI 7계층 모델에서 라우팅(Routing) 기능을 담당하는 계층은?',
    optionA:'데이터 링크 계층(Data Link)', optionB:'네트워크 계층(Network)',
    optionC:'전송 계층(Transport)', optionD:'세션 계층(Session)',
    answer:2, difficulty:'EASY', topic:'네트워크',
    explanation:'네트워크 계층(3계층)은 IP 주소를 사용한 논리적 주소 지정과 라우팅(경로 선택)을 담당합니다. 대표 프로토콜: IP, ICMP, ARP. 데이터 링크 계층은 MAC 주소 기반 프레임 전송을 담당합니다.',
    tags:JSON.stringify(['OSI', '네트워크계층', '라우팅']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'프로그래밍 언어 활용', questionNo:3,
    content:'Python에서 리스트의 마지막 요소를 제거하고 반환하는 메서드는?',
    optionA:'remove()', optionB:'delete()', optionC:'pop()', optionD:'discard()',
    answer:3, difficulty:'EASY', topic:'Python',
    explanation:'pop()은 리스트의 마지막 요소(또는 지정된 인덱스의 요소)를 제거하고 반환합니다. remove()는 특정 값을 찾아 제거하고 반환하지 않습니다. discard()는 집합(set)의 메서드입니다.',
    tags:JSON.stringify(['Python', '리스트']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'프로그래밍 언어 활용', questionNo:4,
    content:'TCP와 UDP의 차이점에 대한 설명으로 옳은 것은?',
    optionA:'UDP는 연결 지향적이고 신뢰성 있는 전송을 보장한다',
    optionB:'TCP는 데이터그램 방식으로 빠른 전송에 적합하다',
    optionC:'TCP는 흐름 제어와 오류 제어 기능을 제공한다',
    optionD:'UDP는 순서 보장과 재전송 기능을 지원한다',
    answer:3, difficulty:'EASY', topic:'네트워크 프로토콜',
    explanation:'TCP는 연결 지향적으로 3-way handshake, 흐름 제어(슬라이딩 윈도우), 오류 제어(재전송), 순서 보장을 제공합니다. UDP는 비연결형으로 이런 기능 없이 빠른 전송에 적합합니다.',
    tags:JSON.stringify(['TCP', 'UDP', '네트워크']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'프로그래밍 언어 활용', questionNo:5,
    content:'Java에서 인터페이스(Interface)와 추상 클래스(Abstract Class)의 차이로 옳은 것은?',
    optionA:'인터페이스는 다중 구현이 불가능하다', optionB:'추상 클래스는 생성자를 가질 수 있다',
    optionC:'인터페이스는 일반 메서드를 가질 수 없다', optionD:'추상 클래스는 멤버 변수를 가질 수 없다',
    answer:2, difficulty:'MEDIUM', topic:'Java',
    explanation:'추상 클래스는 생성자를 가질 수 있으며(직접 인스턴스화 불가), 멤버 변수와 일반 메서드를 포함할 수 있습니다. Java 8 이후 인터페이스도 default/static 메서드를 가질 수 있습니다. 클래스는 여러 인터페이스를 구현 가능하나 추상 클래스는 하나만 상속 가능합니다.',
    tags:JSON.stringify(['Java', '인터페이스', '추상클래스']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'프로그래밍 언어 활용', questionNo:6,
    content:'프로세스 스케줄링 기법 중 선점(Preemptive) 방식이 아닌 것은?',
    optionA:'라운드 로빈(Round Robin)', optionB:'SRT(Shortest Remaining Time)',
    optionC:'SJF(Shortest Job First)', optionD:'다단계 큐(Multi-level Queue)',
    answer:3, difficulty:'MEDIUM', topic:'운영체제',
    explanation:'SJF(Shortest Job First)는 비선점 방식입니다(가장 짧은 작업 우선). SRT는 SJF의 선점 버전. 라운드 로빈은 시간 할당량(Time Quantum) 기반 선점 스케줄링입니다.',
    tags:JSON.stringify(['운영체제', '스케줄링', '선점']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'프로그래밍 언어 활용', questionNo:7,
    content:'페이지 교체 알고리즘 중 가장 오래 사용되지 않은 페이지를 교체하는 알고리즘은?',
    optionA:'FIFO(First In First Out)', optionB:'LRU(Least Recently Used)',
    optionC:'LFU(Least Frequently Used)', optionD:'Optimal(최적)',
    answer:2, difficulty:'EASY', topic:'메모리 관리',
    explanation:'LRU(Least Recently Used)는 가장 최근에 사용되지 않은(오래된) 페이지를 교체합니다. LFU는 사용 빈도가 가장 낮은 페이지, FIFO는 가장 먼저 들어온 페이지, Optimal은 미래에 가장 오랫동안 사용되지 않을 페이지를 교체합니다.',
    tags:JSON.stringify(['페이지교체', 'LRU', '메모리']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'프로그래밍 언어 활용', questionNo:8,
    content:'다음 Python 코드의 출력 결과는?\nresult = [x**2 for x in range(1,4) if x % 2 == 1]\nprint(result)',
    optionA:'[1, 4, 9]', optionB:'[1, 9]', optionC:'[1, 3]', optionD:'[4]',
    answer:2, difficulty:'MEDIUM', topic:'Python',
    explanation:'range(1,4)는 [1,2,3]. 조건 x%2==1 (홀수): 1, 3이 해당. 각각 제곱: 1², 3² = 1, 9. 결과: [1, 9]',
    tags:JSON.stringify(['Python', '리스트 컴프리헨션']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'프로그래밍 언어 활용', questionNo:9,
    content:'교착상태(Deadlock) 발생의 4가지 필요 조건이 아닌 것은?',
    optionA:'상호 배제(Mutual Exclusion)', optionB:'점유 대기(Hold and Wait)',
    optionC:'선점(Preemption)', optionD:'환형 대기(Circular Wait)',
    answer:3, difficulty:'MEDIUM', topic:'운영체제 교착상태',
    explanation:'교착상태 4가지 필요 조건: 상호 배제, 점유 대기, 비선점(Non-preemption), 환형 대기. 선점이 허용되면(비선점이 아니면) 교착상태가 발생하지 않습니다.',
    tags:JSON.stringify(['교착상태', 'Deadlock']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'프로그래밍 언어 활용', questionNo:10,
    content:'C언어에서 포인터 변수 ptr이 배열 arr의 첫 번째 요소를 가리킬 때, *(ptr+2)와 동일한 표현은?',
    optionA:'arr[1]', optionB:'arr[2]', optionC:'*(arr+1)', optionD:'ptr[1]',
    answer:2, difficulty:'MEDIUM', topic:'C언어 포인터',
    explanation:'*(ptr+2)는 ptr이 가리키는 주소에서 2칸 이동한 위치의 값입니다. ptr=arr이므로 *(arr+2) = arr[2]입니다. 포인터 산술에서 ptr+n은 (시작주소 + n×자료형크기)입니다.',
    tags:JSON.stringify(['C언어', '포인터', '배열']), sourceNote:'2024년 1회 스타일' },

  // ===== 정보시스템 구축 관리 2024년 1회 =====
  { year:2024, round:1, subject:'정보시스템 구축 관리', questionNo:1,
    content:'소프트웨어 개발 생명주기(SDLC) 모델 중 위험 분석을 강조하는 모델은?',
    optionA:'폭포수 모델(Waterfall)', optionB:'나선형 모델(Spiral)',
    optionC:'프로토타입 모델(Prototype)', optionD:'RAD(Rapid Application Development)',
    answer:2, difficulty:'EASY', topic:'SDLC 모델',
    explanation:'나선형 모델(Boehm)은 위험 분석을 핵심으로 하며, 계획→위험분석→개발→평가를 반복합니다. 대규모 복잡한 시스템에 적합하며, 위험을 초기에 식별하고 대응합니다.',
    tags:JSON.stringify(['나선형모델', 'SDLC', '위험분석']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'정보시스템 구축 관리', questionNo:2,
    content:'정보보안의 3요소(CIA)에 해당하지 않는 것은?',
    optionA:'기밀성(Confidentiality)', optionB:'무결성(Integrity)',
    optionC:'가용성(Availability)', optionD:'인증성(Authenticity)',
    answer:4, difficulty:'EASY', topic:'정보보안',
    explanation:'정보보안 3요소(CIA 트라이어드): 기밀성(허가된 사용자만 접근), 무결성(데이터의 정확성/완전성 보장), 가용성(필요 시 접근 가능). 인증성은 보안 요소이나 CIA 트라이어드에는 포함되지 않습니다.',
    tags:JSON.stringify(['정보보안', 'CIA']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'정보시스템 구축 관리', questionNo:3,
    content:'PKI(Public Key Infrastructure)에서 인증서 발급 및 관리를 담당하는 기관은?',
    optionA:'RA(Registration Authority)', optionB:'CA(Certificate Authority)',
    optionC:'CRL(Certificate Revocation List)', optionD:'OCSP(Online Certificate Status Protocol)',
    answer:2, difficulty:'MEDIUM', topic:'공개키 인프라',
    explanation:'CA(Certificate Authority, 인증기관)는 공개키 인증서를 발급하고 관리합니다. RA는 사용자 신원 확인 후 CA에 인증서 발급을 요청합니다. CRL은 폐기된 인증서 목록입니다.',
    tags:JSON.stringify(['PKI', 'CA', '인증서']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'정보시스템 구축 관리', questionNo:4,
    content:'소프트웨어 품질 특성을 정의한 국제 표준 ISO/IEC 25010에서 정의하는 품질 특성이 아닌 것은?',
    optionA:'기능 적합성(Functional Suitability)', optionB:'성능 효율성(Performance Efficiency)',
    optionC:'유지보수성(Maintainability)', optionD:'적시성(Timeliness)',
    answer:4, difficulty:'HARD', topic:'소프트웨어 품질',
    explanation:'ISO/IEC 25010(SQuaRE) 8가지 품질 특성: 기능 적합성, 성능 효율성, 호환성, 사용성, 신뢰성, 보안성, 유지보수성, 이식성. 적시성은 포함되지 않습니다.',
    tags:JSON.stringify(['ISO25010', '소프트웨어품질']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'정보시스템 구축 관리', questionNo:5,
    content:'네트워크 보안에서 허가되지 않은 접근을 차단하는 보안 시스템으로, 내부 네트워크와 외부 인터넷 사이에 위치하는 것은?',
    optionA:'IDS(침입 탐지 시스템)', optionB:'IPS(침입 방지 시스템)',
    optionC:'방화벽(Firewall)', optionD:'VPN(가상 사설망)',
    answer:3, difficulty:'EASY', topic:'네트워크 보안',
    explanation:'방화벽(Firewall)은 미리 정의된 규칙에 따라 네트워크 트래픽을 허용/차단하는 보안 장비입니다. 내부망과 외부망 사이에서 접근 제어 역할을 합니다.',
    tags:JSON.stringify(['방화벽', '네트워크보안']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'정보시스템 구축 관리', questionNo:6,
    content:'소프트웨어 유지보수 유형 중 새로운 기능을 추가하거나 기존 기능을 개선하는 것을 목적으로 하는 유지보수는?',
    optionA:'수정(Corrective) 유지보수', optionB:'적응(Adaptive) 유지보수',
    optionC:'완전(Perfective) 유지보수', optionD:'예방(Preventive) 유지보수',
    answer:3, difficulty:'EASY', topic:'소프트웨어 유지보수',
    explanation:'완전(Perfective) 유지보수는 사용자 요구나 성능 개선을 위한 기능 추가/개선을 목적으로 합니다. 수정은 오류 수정, 적응은 환경 변화 대응, 예방은 미래 오류 방지가 목적입니다.',
    tags:JSON.stringify(['유지보수', '완전유지보수']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'정보시스템 구축 관리', questionNo:7,
    content:'프로젝트 관리에서 WBS(Work Breakdown Structure)에 대한 설명으로 옳은 것은?',
    optionA:'프로젝트 일정을 막대 차트로 표현한 것', optionB:'작업을 계층적으로 분류한 구조',
    optionC:'프로젝트 비용을 추정하는 기법', optionD:'위험 요소를 식별하는 문서',
    answer:2, difficulty:'EASY', topic:'프로젝트 관리',
    explanation:'WBS(Work Breakdown Structure)는 프로젝트를 계층적 작업 단위로 분해한 구조로, 전체 범위를 관리 가능한 구성요소로 나눕니다. 막대 차트는 간트 차트(Gantt Chart)입니다.',
    tags:JSON.stringify(['WBS', '프로젝트관리']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'정보시스템 구축 관리', questionNo:8,
    content:'개인정보 보호와 관련하여 "정보 주체가 자신의 개인정보 처리에 동의한 범위 내에서만 이용 가능"하다는 원칙은?',
    optionA:'목적 제한의 원칙', optionB:'데이터 최소화 원칙',
    optionC:'정확성의 원칙', optionD:'저장 제한의 원칙',
    answer:1, difficulty:'MEDIUM', topic:'개인정보보호',
    explanation:'목적 제한의 원칙은 개인정보를 수집 목적의 범위를 초과하여 사용하면 안 된다는 원칙입니다. GDPR의 핵심 원칙 중 하나로, 정보 주체의 동의 범위 내에서만 처리해야 합니다.',
    tags:JSON.stringify(['개인정보보호', 'GDPR']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'정보시스템 구축 관리', questionNo:9,
    content:'클라우드 컴퓨팅의 배포 모델 중 조직 내부에서만 사용하는 전용 클라우드는?',
    optionA:'퍼블릭 클라우드(Public Cloud)', optionB:'프라이빗 클라우드(Private Cloud)',
    optionC:'하이브리드 클라우드(Hybrid Cloud)', optionD:'커뮤니티 클라우드(Community Cloud)',
    answer:2, difficulty:'EASY', topic:'클라우드 컴퓨팅',
    explanation:'프라이빗 클라우드는 단일 조직이 전용으로 사용하는 클라우드로, 높은 보안과 제어력을 제공하나 초기 비용이 높습니다. 퍼블릭은 다수 조직 공유, 하이브리드는 혼합 방식입니다.',
    tags:JSON.stringify(['클라우드', '배포모델']), sourceNote:'2024년 1회 스타일' },

  { year:2024, round:1, subject:'정보시스템 구축 관리', questionNo:10,
    content:'정보 시스템의 재해복구(DR) 목표 지표에서 RTO(Recovery Time Objective)가 의미하는 것은?',
    optionA:'허용 가능한 최대 데이터 손실 기간', optionB:'재해 발생 후 허용 가능한 최대 복구 시간',
    optionC:'시스템 백업 주기', optionD:'데이터 백업 보관 기간',
    answer:2, difficulty:'MEDIUM', topic:'재해복구',
    explanation:'RTO(Recovery Time Objective)는 재해 발생 후 시스템이 복구되어야 하는 목표 시간입니다. RPO(Recovery Point Objective)는 허용 가능한 최대 데이터 손실 기간(마지막 백업으로 돌아갈 수 있는 시점)입니다.',
    tags:JSON.stringify(['재해복구', 'RTO', 'RPO']), sourceNote:'2024년 1회 스타일' },

  // ===== 응용 문제 (isGenerated:true, round:99) =====
  // 소프트웨어 설계 응용 (20문제)
  { year:2024, round:99, subject:'소프트웨어 설계', questionNo:1, isGenerated:true,
    content:'다음 중 싱글톤(Singleton) 패턴이 적합한 사용 사례는?',
    optionA:'여러 종류의 버튼 객체를 생성할 때', optionB:'데이터베이스 연결 객체를 전역적으로 하나만 유지할 때',
    optionC:'복잡한 객체를 단계별로 조립할 때', optionD:'알고리즘을 런타임에 교체할 때',
    answer:2, difficulty:'MEDIUM', topic:'디자인 패턴 응용',
    explanation:'싱글톤 패턴은 클래스의 인스턴스가 하나만 생성되도록 보장합니다. DB 연결, 로그 관리자, 설정 관리자처럼 전역 상태를 단일 객체로 관리할 때 적합합니다.',
    tags:JSON.stringify(['싱글톤', '디자인패턴', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'소프트웨어 설계', questionNo:2, isGenerated:true,
    content:'마이크로서비스 아키텍처에서 서비스 간 통신 방식으로 비동기 메시지 기반을 선택해야 하는 상황은?',
    optionA:'결제 처리처럼 즉시 응답이 필요한 경우', optionB:'사용자 로그인 인증이 필요한 경우',
    optionC:'이메일 발송처럼 처리 지연이 허용되는 경우', optionD:'실시간 재고 확인이 필요한 경우',
    answer:3, difficulty:'HARD', topic:'마이크로서비스 응용',
    explanation:'비동기 메시지 방식(메시지 큐)은 응답 대기 없이 처리할 수 있는 경우에 적합합니다. 이메일 발송, 알림, 배치 처리처럼 지연 허용 작업에 활용합니다. 즉각적인 응답이 필요한 경우 동기 REST/gRPC 방식을 사용합니다.',
    tags:JSON.stringify(['MSA', '비동기통신', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'소프트웨어 설계', questionNo:3, isGenerated:true,
    content:'다음 설명이 가리키는 디자인 패턴은?\n"기존 코드를 변경하지 않고, 새로운 기능을 클래스에 동적으로 추가할 수 있다. 상속 대신 위임(Delegation)을 사용한다."',
    optionA:'어댑터(Adapter)', optionB:'데코레이터(Decorator)', optionC:'퍼사드(Facade)', optionD:'컴포지트(Composite)',
    answer:2, difficulty:'HARD', topic:'디자인 패턴 응용',
    explanation:'데코레이터 패턴은 객체에 기능을 동적으로 추가합니다. Java I/O의 BufferedReader(new FileReader())처럼 래퍼 클래스를 통해 기능을 조합합니다. 상속보다 유연한 기능 확장이 가능합니다.',
    tags:JSON.stringify(['데코레이터', '디자인패턴', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'소프트웨어 설계', questionNo:4, isGenerated:true,
    content:'DIP(의존 역전 원칙)를 올바르게 적용한 것은?',
    optionA:'고수준 모듈이 저수준 모듈의 구체 클래스에 직접 의존한다',
    optionB:'고수준 모듈과 저수준 모듈 모두 추상화에 의존한다',
    optionC:'저수준 모듈이 고수준 모듈을 직접 호출한다',
    optionD:'모든 클래스를 추상 클래스로 대체한다',
    answer:2, difficulty:'HARD', topic:'SOLID 원칙 응용',
    explanation:'DIP(Dependency Inversion Principle): 고수준 모듈은 저수준 모듈에 의존하면 안 되며, 둘 다 추상화(인터페이스/추상 클래스)에 의존해야 합니다. 이를 통해 느슨한 결합과 테스트 용이성이 향상됩니다.',
    tags:JSON.stringify(['DIP', 'SOLID', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'소프트웨어 설계', questionNo:5, isGenerated:true,
    content:'이벤트 소싱(Event Sourcing) 패턴과 CQRS(Command Query Responsibility Segregation) 패턴을 함께 사용하는 주된 이유는?',
    optionA:'데이터베이스 성능을 향상시키기 위해', optionB:'코드 중복을 제거하기 위해',
    optionC:'쓰기(Command)와 읽기(Query) 작업을 분리하고 이벤트 이력을 보존하기 위해',
    optionD:'단일 데이터베이스에서 모든 작업을 처리하기 위해',
    answer:3, difficulty:'HARD', topic:'아키텍처 패턴 응용',
    explanation:'CQRS는 쓰기와 읽기 모델을 분리해 각각 최적화합니다. 이벤트 소싱은 상태 변경을 이벤트 로그로 저장하여 감사 추적과 시점 복구를 가능하게 합니다. 두 패턴의 조합은 MSA와 DDD에서 자주 사용됩니다.',
    tags:JSON.stringify(['CQRS', '이벤트소싱', '응용']), sourceNote:'AI 생성 응용문제' },

  // 소프트웨어 개발 응용 (20문제)
  { year:2024, round:99, subject:'소프트웨어 개발', questionNo:1, isGenerated:true,
    content:'다음 코드에서 재귀 함수의 시간 복잡도는?\nfunction fib(n) { if(n<=1) return n; return fib(n-1)+fib(n-2); }',
    optionA:'O(n)', optionB:'O(n log n)', optionC:'O(2^n)', optionD:'O(n^2)',
    answer:3, difficulty:'HARD', topic:'알고리즘 복잡도 응용',
    explanation:'단순 재귀 피보나치는 중복 계산이 많아 O(2^n)입니다. 메모이제이션(동적 계획법)을 적용하면 O(n)으로 개선됩니다. fib(n)은 fib(n-1)과 fib(n-2)를 각각 호출하므로 이진 트리 형태로 호출 수가 기하급수적으로 증가합니다.',
    tags:JSON.stringify(['재귀', '피보나치', '시간복잡도', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'소프트웨어 개발', questionNo:2, isGenerated:true,
    content:'동적 계획법(Dynamic Programming)이 적합한 문제의 특성이 아닌 것은?',
    optionA:'최적 부분 구조(Optimal Substructure)', optionB:'중복 부분 문제(Overlapping Subproblems)',
    optionC:'그리디 선택 속성(Greedy Choice Property)', optionD:'부분 문제들을 메모이제이션으로 저장 가능',
    answer:3, difficulty:'HARD', topic:'알고리즘 응용',
    explanation:'그리디 선택 속성은 탐욕 알고리즘(Greedy Algorithm)의 특성입니다. 동적 계획법은 최적 부분 구조와 중복 부분 문제 특성이 있을 때 적합합니다. 메모이제이션 또는 타뷸레이션으로 구현합니다.',
    tags:JSON.stringify(['동적계획법', 'DP', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'소프트웨어 개발', questionNo:3, isGenerated:true,
    content:'API 테스트에서 경계값 분석(Boundary Value Analysis)을 적용할 때, 입력 범위가 1~100인 경우 테스트해야 할 값으로 가장 적절한 것은?',
    optionA:'1, 50, 100', optionB:'0, 1, 100, 101',
    optionC:'1, 2, 99, 100', optionD:'0, 1, 2, 99, 100, 101',
    answer:4, difficulty:'HARD', topic:'테스트 기법 응용',
    explanation:'경계값 분석은 경계값과 그 바로 안팎의 값을 테스트합니다. 1~100 범위에서: 최솟값(1), 최솟값-1(0), 최솟값+1(2), 최댓값(100), 최댓값-1(99), 최댓값+1(101)을 모두 테스트하는 것이 완전합니다.',
    tags:JSON.stringify(['경계값분석', '테스트', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'소프트웨어 개발', questionNo:4, isGenerated:true,
    content:'CI/CD 파이프라인에서 "코드 변경 시 자동으로 테스트하고 스테이징 서버에 배포"하는 단계는?',
    optionA:'지속적 통합(CI)만 해당', optionB:'지속적 배포(CD)만 해당',
    optionC:'CI와 CD 모두 해당', optionD:'지속적 모니터링(CM)에 해당',
    answer:3, difficulty:'MEDIUM', topic:'개발 프로세스 응용',
    explanation:'CI(Continuous Integration)는 코드 변경 시 자동 빌드/테스트를, CD(Continuous Delivery/Deployment)는 자동 배포를 담당합니다. 스테이징까지 자동 배포는 CI+CD 파이프라인 전체가 동작하는 것입니다.',
    tags:JSON.stringify(['CICD', '데브옵스', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'소프트웨어 개발', questionNo:5, isGenerated:true,
    content:'Graph에서 최단 경로를 구하는 다익스트라(Dijkstra) 알고리즘이 동작하지 않는 경우는?',
    optionA:'가중치가 없는 그래프', optionB:'방향 그래프', optionC:'음의 가중치가 있는 그래프', optionD:'비연결 그래프',
    answer:3, difficulty:'HARD', topic:'알고리즘 응용',
    explanation:'다익스트라 알고리즘은 음의 가중치 간선이 있으면 올바른 결과를 보장하지 않습니다. 음의 가중치가 있는 경우 벨만-포드(Bellman-Ford) 알고리즘을 사용해야 합니다.',
    tags:JSON.stringify(['다익스트라', '최단경로', '응용']), sourceNote:'AI 생성 응용문제' },

  // 데이터베이스 구축 응용 (20문제)
  { year:2024, round:99, subject:'데이터베이스 구축', questionNo:1, isGenerated:true,
    content:'다음 SQL을 실행했을 때 결과 행의 개수는?\nSELECT A.id FROM A LEFT JOIN B ON A.id=B.a_id WHERE B.a_id IS NULL;\n(A: 5행, B: B.a_id에 A.id 1,2,3 존재)',
    optionA:'0개', optionB:'2개', optionC:'3개', optionD:'5개',
    answer:2, difficulty:'HARD', topic:'SQL 응용',
    explanation:'LEFT JOIN 후 B.a_id IS NULL은 B에 매칭되지 않는 A의 행만 필터링합니다(LEFT ANTI JOIN). A.id 4, 5가 B에 없으므로 2개 반환됩니다.',
    tags:JSON.stringify(['SQL', 'JOIN', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'데이터베이스 구축', questionNo:2, isGenerated:true,
    content:'다음과 같은 테이블이 있을 때 제3정규형(3NF)을 위반하는 경우는?\n(학번, 과목코드, 성적, 교수명, 교수연구실)',
    optionA:'학번→성적 종속', optionB:'(학번,과목코드)→성적 종속',
    optionC:'과목코드→교수명→교수연구실 이행 함수 종속', optionD:'학번→과목코드 종속',
    answer:3, difficulty:'HARD', topic:'정규화 응용',
    explanation:'3NF 위반: 이행 함수 종속(Transitive Dependency) - 기본키가 아닌 속성(교수명)이 다른 비키 속성(교수연구실)을 결정하는 경우입니다. 과목코드→교수명→교수연구실 관계가 이에 해당합니다.',
    tags:JSON.stringify(['3NF', '정규화', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'데이터베이스 구축', questionNo:3, isGenerated:true,
    content:'동시성 제어에서 낙관적 잠금(Optimistic Locking)이 비관적 잠금(Pessimistic Locking)보다 유리한 상황은?',
    optionA:'데이터 충돌이 자주 발생하는 환경', optionB:'읽기가 많고 충돌이 드문 환경',
    optionC:'금융 거래처럼 데이터 일관성이 절대적으로 중요한 환경', optionD:'배타적 쓰기가 빈번한 환경',
    answer:2, difficulty:'HARD', topic:'동시성 제어 응용',
    explanation:'낙관적 잠금은 충돌이 드물다고 가정하여 수정 시점에 버전 번호로 충돌을 감지합니다. 읽기가 많고 쓰기가 드문 환경에서 성능이 좋습니다. 충돌이 잦은 환경에서는 재시도 오버헤드로 오히려 성능이 저하됩니다.',
    tags:JSON.stringify(['동시성제어', '낙관적잠금', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'데이터베이스 구축', questionNo:4, isGenerated:true,
    content:'파티셔닝(Partitioning)과 샤딩(Sharding)의 차이점으로 옳은 것은?',
    optionA:'파티셔닝은 여러 서버에 분산, 샤딩은 단일 서버 내 분할',
    optionB:'파티셔닝은 단일 DB 내 테이블 분할, 샤딩은 여러 DB 서버에 분산',
    optionC:'두 기법은 동일하며 용어만 다르다',
    optionD:'샤딩은 수직 분할, 파티셔닝은 수평 분할만 가능하다',
    answer:2, difficulty:'HARD', topic:'DB 확장성 응용',
    explanation:'파티셔닝은 단일 DB 서버 내에서 테이블을 물리적으로 분할합니다. 샤딩은 동일한 스키마의 데이터를 여러 DB 서버에 분산합니다(수평적 확장). 샤딩은 파티셔닝의 확장된 개념입니다.',
    tags:JSON.stringify(['파티셔닝', '샤딩', 'DB확장', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'데이터베이스 구축', questionNo:5, isGenerated:true,
    content:'다음 SQL에서 서브쿼리 최적화 방법으로 가장 적절한 것은?\nSELECT * FROM orders WHERE customer_id IN (SELECT id FROM customers WHERE city=\'Seoul\');',
    optionA:'서브쿼리를 그대로 유지한다', optionB:'JOIN으로 변환한다',
    optionC:'중첩 루프로 변환한다', optionD:'UNION으로 변환한다',
    answer:2, difficulty:'HARD', topic:'SQL 최적화 응용',
    explanation:'IN 서브쿼리는 일반적으로 JOIN으로 변환하면 쿼리 옵티마이저가 더 효율적인 실행 계획을 선택합니다: SELECT o.* FROM orders o JOIN customers c ON o.customer_id=c.id WHERE c.city=\'Seoul\'',
    tags:JSON.stringify(['SQL최적화', '서브쿼리', '응용']), sourceNote:'AI 생성 응용문제' },

  // 프로그래밍 언어 활용 응용 (20문제)
  { year:2024, round:99, subject:'프로그래밍 언어 활용', questionNo:1, isGenerated:true,
    content:'다음 Java 코드의 출력 결과는?\nString a = "hello";\nString b = "hello";\nString c = new String("hello");\nSystem.out.println(a==b);\nSystem.out.println(a==c);',
    optionA:'true true', optionB:'true false', optionC:'false false', optionD:'false true',
    answer:2, difficulty:'HARD', topic:'Java 응용',
    explanation:'a==b는 true: 문자열 리터럴은 String Pool에서 같은 객체를 참조합니다. a==c는 false: new String()은 Heap에 새 객체를 생성하므로 다른 참조입니다. 값 비교는 equals() 사용해야 합니다.',
    tags:JSON.stringify(['Java', 'String', '참조비교', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'프로그래밍 언어 활용', questionNo:2, isGenerated:true,
    content:'REST API 설계 원칙에서 올바른 HTTP 메서드 사용은?',
    optionA:'GET /users/delete/1 - 사용자 삭제', optionB:'DELETE /users/1 - 사용자 삭제',
    optionC:'POST /users/1/get - 사용자 조회', optionD:'GET /users - 사용자 생성',
    answer:2, difficulty:'MEDIUM', topic:'REST API 응용',
    explanation:'RESTful API: GET(조회), POST(생성), PUT/PATCH(수정), DELETE(삭제). URI에 행위를 포함하면 안 됩니다. DELETE /users/1이 올바른 RESTful 설계입니다.',
    tags:JSON.stringify(['REST', 'API', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'프로그래밍 언어 활용', questionNo:3, isGenerated:true,
    content:'다음 Python 코드의 실행 결과는?\ndef gen():\n    yield 1\n    yield 2\n    yield 3\ng = gen()\nprint(next(g), next(g))',
    optionA:'1 2', optionB:'1 1', optionC:'[1,2,3] [1,2,3]', optionD:'오류 발생',
    answer:1, difficulty:'HARD', topic:'Python 제너레이터 응용',
    explanation:'제너레이터는 yield로 값을 하나씩 반환합니다. next(g)를 처음 호출하면 yield 1에서 멈추고 1 반환, 두 번째 호출 시 yield 2에서 멈추고 2 반환합니다. 결과: 1 2',
    tags:JSON.stringify(['Python', '제너레이터', 'yield', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'프로그래밍 언어 활용', questionNo:4, isGenerated:true,
    content:'운영체제에서 프로세스와 스레드의 차이로 옳은 것은?',
    optionA:'스레드는 독립된 메모리 공간을 가진다', optionB:'프로세스는 같은 프로세스 내 자원을 공유한다',
    optionC:'스레드는 같은 프로세스 내에서 스택만 독립적으로 가진다', optionD:'프로세스 생성이 스레드 생성보다 빠르다',
    answer:3, difficulty:'HARD', topic:'운영체제 응용',
    explanation:'같은 프로세스의 스레드들은 코드, 데이터, 힙, 파일을 공유하지만 스택(지역변수, 반환주소)과 레지스터는 각자 독립적으로 가집니다. 프로세스 생성은 스레드보다 오버헤드가 큽니다.',
    tags:JSON.stringify(['프로세스', '스레드', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'프로그래밍 언어 활용', questionNo:5, isGenerated:true,
    content:'HTTPS에서 SSL/TLS 핸드셰이크 과정에서 서버가 클라이언트에게 보내는 것이 아닌 것은?',
    optionA:'서버 인증서', optionB:'서버의 공개키', optionC:'클라이언트의 비밀키', optionD:'지원하는 암호화 방식 목록',
    answer:3, difficulty:'HARD', topic:'네트워크 보안 응용',
    explanation:'SSL/TLS 핸드셰이크: 서버는 인증서(공개키 포함), 지원 암호화 방식을 전송합니다. 비밀키는 클라이언트가 서버 공개키로 암호화한 Pre-Master Secret으로 협상하며, 서버의 비밀키는 절대 전송하지 않습니다.',
    tags:JSON.stringify(['HTTPS', 'TLS', '핸드셰이크', '응용']), sourceNote:'AI 생성 응용문제' },

  // 정보시스템 구축 관리 응용 (20문제)
  { year:2024, round:99, subject:'정보시스템 구축 관리', questionNo:1, isGenerated:true,
    content:'소프트웨어 개발 비용 산정 기법 중 기능 점수(Function Point)에 영향을 주지 않는 것은?',
    optionA:'외부 입력(External Input)', optionB:'내부 논리 파일(Internal Logical File)',
    optionC:'외부 조회(External Inquiry)', optionD:'코드 라인 수(LOC)',
    answer:4, difficulty:'HARD', topic:'비용 산정 응용',
    explanation:'기능 점수법은 기능 관점의 측정으로, LOC(코드 라인 수)와 무관합니다. 기능 점수 구성: 외부 입력(EI), 외부 출력(EO), 외부 조회(EQ), 내부 논리 파일(ILF), 외부 인터페이스 파일(EIF)',
    tags:JSON.stringify(['기능점수', '비용산정', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'정보시스템 구축 관리', questionNo:2, isGenerated:true,
    content:'DevSecOps에서 "Shift Left Security"가 의미하는 것은?',
    optionA:'보안 테스트를 개발 완료 후에 집중적으로 수행', optionB:'보안을 개발 초기 단계부터 통합하는 접근법',
    optionC:'보안 전담 팀을 별도로 운영하는 방식', optionD:'좌측 방향으로 코드 리뷰를 진행하는 방법',
    answer:2, difficulty:'HARD', topic:'DevSecOps 응용',
    explanation:'Shift Left Security는 보안을 개발 사이클 초기(왼쪽)로 이동시키는 개념입니다. SAST, 코드 리뷰, 보안 요구사항 분석을 개발 초기에 수행하여 나중에 발견하는 것보다 비용을 절감합니다.',
    tags:JSON.stringify(['DevSecOps', 'ShiftLeft', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'정보시스템 구축 관리', questionNo:3, isGenerated:true,
    content:'랜섬웨어(Ransomware) 감염 예방 방법으로 가장 효과적인 것은?',
    optionA:'공인된 백신 소프트웨어 하나만 사용', optionB:'정기적인 오프라인 백업 유지',
    optionC:'모든 파일을 클라우드에 저장', optionD:'인터넷 연결 속도 향상',
    answer:2, difficulty:'MEDIUM', topic:'보안 위협 응용',
    explanation:'랜섬웨어는 파일을 암호화하여 복호화 대가로 금전을 요구합니다. 오프라인(air-gap) 백업은 감염된 네트워크와 격리되어 복구 가능한 유일한 수단입니다. 클라우드 백업도 동기화 시 감염될 수 있습니다.',
    tags:JSON.stringify(['랜섬웨어', '보안', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'정보시스템 구축 관리', questionNo:4, isGenerated:true,
    content:'애자일 프로젝트에서 스크럼 마스터의 역할로 옳지 않은 것은?',
    optionA:'팀의 장애물(Impediment) 제거를 돕는다', optionB:'데일리 스크럼을 진행한다',
    optionC:'제품 백로그(Product Backlog) 우선순위를 결정한다', optionD:'스크럼 프로세스가 올바르게 진행되도록 코치한다',
    answer:3, difficulty:'MEDIUM', topic:'애자일 관리 응용',
    explanation:'제품 백로그 우선순위 결정은 제품 책임자(Product Owner)의 역할입니다. 스크럼 마스터는 프로세스 촉진자로서 장애물 제거, 스크럼 규칙 준수, 팀 보호 역할을 합니다.',
    tags:JSON.stringify(['스크럼', '스크럼마스터', '응용']), sourceNote:'AI 생성 응용문제' },

  { year:2024, round:99, subject:'정보시스템 구축 관리', questionNo:5, isGenerated:true,
    content:'제로 트러스트(Zero Trust) 보안 모델의 핵심 원칙은?',
    optionA:'내부 네트워크는 신뢰하고 외부만 검증한다', optionB:'모든 사용자와 디바이스를 항상 검증한다',
    optionC:'한 번 인증한 사용자는 내부에서 자유롭게 접근한다', optionD:'방화벽만으로 보안을 유지한다',
    answer:2, difficulty:'MEDIUM', topic:'보안 아키텍처 응용',
    explanation:'Zero Trust 모델은 "절대 신뢰하지 말고 항상 검증하라(Never Trust, Always Verify)"는 원칙입니다. 내부 네트워크도 신뢰하지 않으며, 모든 접근에 대해 인증/인가/암호화를 적용합니다.',
    tags:JSON.stringify(['제로트러스트', '보안', '응용']), sourceNote:'AI 생성 응용문제' },
]

async function main() {
  console.log('2024 기출 스타일 + 응용문제 시딩...')

  let created = 0, skipped = 0
  for (const q of questions2024) {
    try {
      await prisma.question.upsert({
        where: { year_round_subject_questionNo: { year: q.year, round: q.round, subject: q.subject, questionNo: q.questionNo } },
        create: q,
        update: {},
      })
      created++
    } catch {
      skipped++
    }
  }

  const total = await prisma.question.count()
  console.log(`✓ 새 문제 ${created}개 추가 (스킵: ${skipped}개)`)
  console.log(`📚 전체 문제: ${total}개`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
